
Pool shape : torch.Size([40000, 1, 28, 28])
Starting epig acquisition
Using original estimate_epig function
[run_image_classification_40k_epig_acq.py:150]INFO: Initial test log-likelihood: -2.4580
[run_image_classification_40k_epig_acq.py:151]INFO: Initial test Bayes log-likelihood: -2.1481
[run_image_classification_40k_epig_acq.py:152]INFO: Initial accuracy: 61.17%
We are in concat
[run_image_classification_40k_epig_acq.py:191]INFO: Test log-likelihood at 21: -2.8156
[run_image_classification_40k_epig_acq.py:192]INFO: Test Bayes log-likelihood at 21: -2.1700
[run_image_classification_40k_epig_acq.py:193]INFO: Test accuracy: 60.85%
Starting epig acquisition
Using original estimate_epig function
We are in concat
Starting epig acquisition
Using original estimate_epig function
[run_image_classification_40k_epig_acq.py:191]INFO: Test log-likelihood at 22: -2.3737
[run_image_classification_40k_epig_acq.py:192]INFO: Test Bayes log-likelihood at 22: -2.1430
[run_image_classification_40k_epig_acq.py:193]INFO: Test accuracy: 63.75%
We are in concat
[run_image_classification_40k_epig_acq.py:191]INFO: Test log-likelihood at 23: -2.1192
[run_image_classification_40k_epig_acq.py:192]INFO: Test Bayes log-likelihood at 23: -2.1659
[run_image_classification_40k_epig_acq.py:193]INFO: Test accuracy: 65.26%
Starting epig acquisition
Using original estimate_epig function
We are in concat
Starting epig acquisition
Using original estimate_epig function
[run_image_classification_40k_epig_acq.py:191]INFO: Test log-likelihood at 24: -2.3163
[run_image_classification_40k_epig_acq.py:192]INFO: Test Bayes log-likelihood at 24: -2.1137
[run_image_classification_40k_epig_acq.py:193]INFO: Test accuracy: 65.06%
We are in concat
Starting epig acquisition
Using original estimate_epig function
[run_image_classification_40k_epig_acq.py:191]INFO: Test log-likelihood at 25: -2.3428
[run_image_classification_40k_epig_acq.py:192]INFO: Test Bayes log-likelihood at 25: -2.1289
[run_image_classification_40k_epig_acq.py:193]INFO: Test accuracy: 65.66%
We are in concat
[run_image_classification_40k_epig_acq.py:191]INFO: Test log-likelihood at 26: -3.3019
[run_image_classification_40k_epig_acq.py:192]INFO: Test Bayes log-likelihood at 26: -2.1460
[run_image_classification_40k_epig_acq.py:193]INFO: Test accuracy: 60.27%
Starting epig acquisition
Using original estimate_epig function
We are in concat
[run_image_classification_40k_epig_acq.py:191]INFO: Test log-likelihood at 27: -2.2305
[run_image_classification_40k_epig_acq.py:192]INFO: Test Bayes log-likelihood at 27: -2.1299
[run_image_classification_40k_epig_acq.py:193]INFO: Test accuracy: 65.04%
Starting epig acquisition
Using original estimate_epig function
We are in concat
Starting epig acquisition
Using original estimate_epig function
[run_image_classification_40k_epig_acq.py:191]INFO: Test log-likelihood at 28: -2.4833
[run_image_classification_40k_epig_acq.py:192]INFO: Test Bayes log-likelihood at 28: -2.1086
[run_image_classification_40k_epig_acq.py:193]INFO: Test accuracy: 63.89%
We are in concat
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_image_classification_40k_epig_acq.py", line 259, in <module>
    main(**args)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_image_classification_40k_epig_acq.py", line 181, in main
    dataset.add_ix(dataset.not_ixs[acquired_pool_inds])
IndexError: index 39997 is out of bounds for axis 0 with size 39972
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_image_classification_40k_epig_acq.py", line 259, in <module>
    main(**args)
  File "/dss/dsshome1/0D/ge32jaq2/epig_plus_orig_marglik/active_learning_marglik/run_image_classification_40k_epig_acq.py", line 181, in main
    dataset.add_ix(dataset.not_ixs[acquired_pool_inds])
IndexError: index 39997 is out of bounds for axis 0 with size 39972